/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'id' : bigint,
  'status' : BetStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'betType' : string,
  'gameId' : string,
  'updatedAt' : bigint,
  'amount' : bigint,
  'betNumber' : string,
}
export type BetStatus = { 'won' : null } |
  { 'pending' : null } |
  { 'lost' : null };
export interface Game {
  'id' : string,
  'closeTime' : bigint,
  'name' : string,
  'session' : string,
  'openTime' : bigint,
}
export interface GameResult {
  'panelClose' : string,
  'gameId' : string,
  'jodiNumber' : string,
  'closeNumber' : string,
  'panelOpen' : string,
  'openNumber' : string,
}
export interface Transaction {
  'userId' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'txType' : string,
  'amount' : bigint,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'googleEmail' : string,
  'phone' : string,
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Withdrawal {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'method' : { 'upi' : string } |
    { 'bank' : [string, string, string] },
  'userId' : Principal,
  'timestamp' : bigint,
  'details' : string,
  'amount' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGame' : ActorMethod<[Game], undefined>,
  'addGameResult' : ActorMethod<[GameResult], undefined>,
  'addMoney' : ActorMethod<[string, bigint], undefined>,
  'approveWithdrawal' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGame' : ActorMethod<[string], undefined>,
  'getAllBets' : ActorMethod<[], Array<Bet>>,
  'getAllTransactions' : ActorMethod<
    [],
    Array<[Principal, Array<Transaction>]>
  >,
  'getAllWithdrawals' : ActorMethod<[], Array<Withdrawal>>,
  'getBets' : ActorMethod<[string], Array<Bet>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGame' : ActorMethod<[string], [] | [Game]>,
  'getGameResult' : ActorMethod<[string], [] | [GameResult]>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getUserEmailFromToken' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[string], bigint>,
  'getWithdrawals' : ActorMethod<[string], Array<Withdrawal>>,
  'isAdminCheck' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], string>,
  'loginWithGoogle' : ActorMethod<[string, string, boolean, string], string>,
  'placeBet' : ActorMethod<[string, string, string, string, bigint], undefined>,
  'register' : ActorMethod<[string, string, string], string>,
  'rejectWithdrawal' : ActorMethod<[bigint], undefined>,
  'requestWithdrawal' : ActorMethod<
    [
      string,
      bigint,
      { 'upi' : string } |
        { 'bank' : [string, string, string] },
      string,
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'settleBet' : ActorMethod<[bigint, boolean], undefined>,
  'updateGame' : ActorMethod<[Game], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];