/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Game = IDL.Record({
  'id' : IDL.Text,
  'closeTime' : IDL.Int,
  'name' : IDL.Text,
  'session' : IDL.Text,
  'openTime' : IDL.Int,
});
export const GameResult = IDL.Record({
  'panelClose' : IDL.Text,
  'gameId' : IDL.Text,
  'jodiNumber' : IDL.Text,
  'closeNumber' : IDL.Text,
  'panelOpen' : IDL.Text,
  'openNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BetStatus = IDL.Variant({
  'won' : IDL.Null,
  'pending' : IDL.Null,
  'lost' : IDL.Null,
});
export const Bet = IDL.Record({
  'id' : IDL.Nat,
  'status' : BetStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'betType' : IDL.Text,
  'gameId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'amount' : IDL.Nat,
  'betNumber' : IDL.Text,
});
export const Transaction = IDL.Record({
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'txType' : IDL.Text,
  'amount' : IDL.Int,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Withdrawal = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'method' : IDL.Variant({
    'upi' : IDL.Text,
    'bank' : IDL.Tuple(IDL.Text, IDL.Text, IDL.Text),
  }),
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'googleEmail' : IDL.Text,
  'phone' : IDL.Text,
  'walletBalance' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGame' : IDL.Func([Game], [], []),
  'addGameResult' : IDL.Func([GameResult], [], []),
  'addMoney' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGame' : IDL.Func([IDL.Text], [], []),
  'getAllBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getAllTransactions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Transaction)))],
      ['query'],
    ),
  'getAllWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
  'getBets' : IDL.Func([IDL.Text], [IDL.Vec(Bet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGame' : IDL.Func([IDL.Text], [IDL.Opt(Game)], ['query']),
  'getGameResult' : IDL.Func([IDL.Text], [IDL.Opt(GameResult)], ['query']),
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
  'getUserEmailFromToken' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getWithdrawals' : IDL.Func([IDL.Text], [IDL.Vec(Withdrawal)], ['query']),
  'isAdminCheck' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'loginWithGoogle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [IDL.Text],
      [],
    ),
  'placeBet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Variant({
          'upi' : IDL.Text,
          'bank' : IDL.Tuple(IDL.Text, IDL.Text, IDL.Text),
        }),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'settleBet' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateGame' : IDL.Func([Game], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Game = IDL.Record({
    'id' : IDL.Text,
    'closeTime' : IDL.Int,
    'name' : IDL.Text,
    'session' : IDL.Text,
    'openTime' : IDL.Int,
  });
  const GameResult = IDL.Record({
    'panelClose' : IDL.Text,
    'gameId' : IDL.Text,
    'jodiNumber' : IDL.Text,
    'closeNumber' : IDL.Text,
    'panelOpen' : IDL.Text,
    'openNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BetStatus = IDL.Variant({
    'won' : IDL.Null,
    'pending' : IDL.Null,
    'lost' : IDL.Null,
  });
  const Bet = IDL.Record({
    'id' : IDL.Nat,
    'status' : BetStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'betType' : IDL.Text,
    'gameId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'amount' : IDL.Nat,
    'betNumber' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'txType' : IDL.Text,
    'amount' : IDL.Int,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Withdrawal = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'method' : IDL.Variant({
      'upi' : IDL.Text,
      'bank' : IDL.Tuple(IDL.Text, IDL.Text, IDL.Text),
    }),
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'googleEmail' : IDL.Text,
    'phone' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGame' : IDL.Func([Game], [], []),
    'addGameResult' : IDL.Func([GameResult], [], []),
    'addMoney' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGame' : IDL.Func([IDL.Text], [], []),
    'getAllBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getAllTransactions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Transaction)))],
        ['query'],
      ),
    'getAllWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
    'getBets' : IDL.Func([IDL.Text], [IDL.Vec(Bet)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGame' : IDL.Func([IDL.Text], [IDL.Opt(Game)], ['query']),
    'getGameResult' : IDL.Func([IDL.Text], [IDL.Opt(GameResult)], ['query']),
    'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
    'getUserEmailFromToken' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getWithdrawals' : IDL.Func([IDL.Text], [IDL.Vec(Withdrawal)], ['query']),
    'isAdminCheck' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'loginWithGoogle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [IDL.Text],
        [],
      ),
    'placeBet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Variant({
            'upi' : IDL.Text,
            'bank' : IDL.Tuple(IDL.Text, IDL.Text, IDL.Text),
          }),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'settleBet' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateGame' : IDL.Func([Game], [], []),
  });
};

export const init = ({ IDL }) => { return []; };